#remote_theme: zendesk/jekyll-theme-zendesk-garden@v0.3.0
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

sidebar:
  - about
  - philosophy
  - architecture
  - label: Three Pillars
    children:
      - symbolmatch
      - symbolverse
      - symbolprose
  - examples
