remote_theme: zendesk/jekyll-theme-zendesk-garden@v0.3.0

sidebar:
  - about
  - philosophy
  - architecture
  - label: The Three Pillars
    children:
      - symbolmatch
      - symbolverse
      - symbolprose
  - examples
